name: Veracode Static Code Analysis - From Notification service

run-name: Static Code Analysis From Notification service - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [java-maven-pipeline-scan, 
            java-gradle-pipeline-scan, 
            source-code-pipeline-scan, 
            dot-net-pipeline-scan, 
            go-pipeline-scan, 
            dot-net-policy-scan, 
            java-maven-policy-scan, 
            java-gradle-policy-scan, 
            source-code-policy-scan, 
            go-policy-scan]

jobs:
  register:
    echo "Hello world From Notification service"
