name: Veracode Static Code Analysis From Notification service

run-name: Static Code Analysis From Notification service - ${{ github.event.client_payload.repository.name }}

on: push

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
